### ISSUE TITLE
Spreadsheet Example

### ISSUE THREAD

**Issue by dbfy** [RuMont/DiscordSheet#2]
Hello again, can you give us an example of the spread sheet data? I'm running into errors when using $show {name}, mainly I believe because I do not the know icon format for it to parse.

`
/home/ubuntu/DiscordSheet/index.js:107
                        mainwpn = row[6].replace(/ /, '');
                                         ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at /home/ubuntu/DiscordSheet/index.js:107:42
    at Array.map (<anonymous>)
    at /home/ubuntu/DiscordSheet/index.js:103:22
    at /home/ubuntu/DiscordSheet/node_modules/googleapis-common/build/src/apirequest.js:48:53
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by RuMont** [comment]
You may need to adjust the code to match your columns, it is throwing undefined because your data cell is empty.

Given the following sheet
![image](https://user-images.githubusercontent.com/73307917/143875474-a61c0be1-b120-449c-b690-107cb0c403bb.png)
I would change row[6] for row[3] because the main weapon is stored in the 4th position.

The icons are stored in the nwiconsblack folder.

Tell me if this solved your problem.

**Comment by dbfy** [comment]
Thank you very much, problem is fixed. I appreciate the time in your response and your overall help. Have a good week!
